# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: pull latest code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build docker image
        run: |
          docker build -t recmreminder:0.1 . --build-arg MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} --build-arg MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          docker save -o recmreminder.tar recmreminder:0.1

      - name: delete old docker image
        run: sshpass -p ${{secrets.REMOTE_SERVER_HW_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_SERVER_HW_IP}} "docker stop recmreminder || true && docker rm recmreminder || true docker rmi recmreminder:0.1 || true"

      - name: delete old docker tar
        run: sshpass -p ${{secrets.REMOTE_SERVER_HW_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_SERVER_HW_IP}} "cd ${{secrets.REMOTE_PROJECT_CATALOGUE}} && rm -f recmreminder.tar"

      - name: upload new docker image and start up script
        run: sshpass -p ${{secrets.REMOTE_SERVER_HW_PWD}} scp -o StrictHostKeyChecking=no ./recmreminder.tar root@${{secrets.REMOTE_SERVER_HW_IP}}:${{secrets.REMOTE_PROJECT_CATALOGUE}}

      - name: load new docker image
        run: sshpass -p ${{secrets.REMOTE_SERVER_HW_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_SERVER_HW_IP}} "docker load -i ${{secrets.REMOTE_PROJECT_CATALOGUE}}/recmreminder.tar"

      - name: run project
        run: sshpass -p ${{secrets.REMOTE_SERVER_HW_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_SERVER_HW_IP}} "docker run -d -p 9292:9292 --name recmreminder recmreminder:0.1"